# .github/workflows/main_ecristudenthubapp.yml

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ecristudenthubapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ecristudenthubacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_9a2f5b4de2e0428ab98af9be81b305ef }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d487bc7b20e74a8eb1e30d6603b1d492 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ecristudenthubacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9a2f5b4de2e0428ab98af9be81b305ef }}/backend:${{ github.sha }}
        file: ./backend/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecristudenthubapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fd69f58df2024a6e909874cbd58f4bc7 }}
        images: 'ecristudenthubacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_9a2f5b4de2e0428ab98af9be81b305ef }}/backend:${{ github.sha }}'
