# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ecristudenthub-frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ecristudenthubacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_02ab98e987e146c282843c7007f609d9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0e5d724dedc74bc0bf044058330ff850 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ecristudenthubacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_02ab98e987e146c282843c7007f609d9 }}/ecristudenthubacr/frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ecristudenthub-frontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_234bf57075e34acbb97f0786a71e29fd }}
        images: 'ecristudenthubacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_02ab98e987e146c282843c7007f609d9 }}/ecristudenthubacr/frontend:${{ github.sha }}'